workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    # working_directory: mobile
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - android/.gradle
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Bump version
        script: |
          #!/bin/bash
          ver=$(grep '^version:' pubspec.yaml | awk '{print $2}')
          name="${ver%%+*}"
          major=$(echo "$name" | awk -F. '{print $1}')
          minor=$(echo "$name" | awk -F. '{print $2}')
          patch=$(echo "$name" | awk -F. '{print $3}')
          new_patch=$((patch+1))
          new_build="${major}${minor}${new_patch}"
          new_ver="${major}.${minor}.${new_patch}+${new_build}"
          sed -i.bak "s/^version: .*/version: $new_ver/" pubspec.yaml
          echo "New version: $new_ver"
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release --dart-define=ENV=prod | tee build_log_android.txt
    artifacts:
      - build/app/outputs/**/*.apk
      - build_log_android.txt

  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    cache:
      cache_paths:
        - $HOME/.pub-cache
        - ios/Pods
    integrations:
      # app_store_connect: app-publish
      app_store_connect: kotabi_test

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        # bundle_identifier: com.kotabi.app
        bundle_identifier: com.kotabi.app
    scripts:
      - name: Bump version
        script: |
          #!/bin/bash
          ver=$(grep '^version:' pubspec.yaml | awk '{print $2}')
          name="${ver%%+*}"
          major=$(echo "$name" | awk -F. '{print $1}')
          minor=$(echo "$name" | awk -F. '{print $2}')
          patch=$(echo "$name" | awk -F. '{print $3}')
          new_patch=$((patch+1))
          new_build="${major}${minor}${new_patch}"
          new_ver="${major}.${minor}.${new_patch}+${new_build}"
          sed -i.bak "s/^version: .*/version: $new_ver/" pubspec.yaml
          echo "New version: $new_ver"
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Build iOS IPA
        script: |
          flutter build ipa --release --dart-define=ENV=prod --export-options-plist=/Users/builder/export_options.plist | tee build_log_ios.txt

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - build_log_ios.txt

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
