workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    working_directory: mobile
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - mobile/build/app/outputs/**/*.apk

  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    working_directory: mobile

    integrations:
      app_store_connect: japanese-kotabi

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files com.kotabi.app --type IOS_APP_STORE --create
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect certificates list --type IOS_DISTRIBUTION --save
          xcode-project use-profiles

      - name: Build iOS IPA
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true