-- 清空现有数据
DELETE FROM kana;

-- 五十音 - Gojuon (基本50音 × 2种脚本)
INSERT INTO kana (id, type, character, romanization, category, order_index, created_at, updated_at) VALUES
(UUID(), 'hiragana', 'あ', 'a', 'normal', 1, NOW(), NOW()),
(UUID(), 'hiragana', 'い', 'i', 'normal', 2, NOW(), NOW()),
(UUID(), 'hiragana', 'う', 'u', 'normal', 3, NOW(), NOW()),
(UUID(), 'hiragana', 'え', 'e', 'normal', 4, NOW(), NOW()),
(UUID(), 'hiragana', 'お', 'o', 'normal', 5, NOW(), NOW()),
(UUID(), 'hiragana', 'か', 'ka', 'normal', 6, NOW(), NOW()),
(UUID(), 'hiragana', 'き', 'ki', 'normal', 7, NOW(), NOW()),
(UUID(), 'hiragana', 'く', 'ku', 'normal', 8, NOW(), NOW()),
(UUID(), 'hiragana', 'け', 'ke', 'normal', 9, NOW(), NOW()),
(UUID(), 'hiragana', 'こ', 'ko', 'normal', 10, NOW(), NOW()),
(UUID(), 'katakana', 'ア', 'a', 'normal', 11, NOW(), NOW()),
(UUID(), 'katakana', 'イ', 'i', 'normal', 12, NOW(), NOW()),
(UUID(), 'katakana', 'ウ', 'u', 'normal', 13, NOW(), NOW()),
(UUID(), 'katakana', 'エ', 'e', 'normal', 14, NOW(), NOW()),
(UUID(), 'katakana', 'オ', 'o', 'normal', 15, NOW(), NOW()),
(UUID(), 'katakana', 'カ', 'ka', 'normal', 16, NOW(), NOW()),
(UUID(), 'katakana', 'キ', 'ki', 'normal', 17, NOW(), NOW()),
(UUID(), 'katakana', 'ク', 'ku', 'normal', 18, NOW(), NOW()),
(UUID(), 'katakana', 'ケ', 'ke', 'normal', 19, NOW(), NOW()),
(UUID(), 'katakana', 'コ', 'ko', 'normal', 20, NOW(), NOW()),

-- 濁音 - Dakuten (10×2)
(UUID(), 'hiragana', 'が', 'ga', 'dakuten', 21, NOW(), NOW()),
(UUID(), 'hiragana', 'ぎ', 'gi', 'dakuten', 22, NOW(), NOW()),
(UUID(), 'hiragana', 'ぐ', 'gu', 'dakuten', 23, NOW(), NOW()),
(UUID(), 'hiragana', 'げ', 'ge', 'dakuten', 24, NOW(), NOW()),
(UUID(), 'hiragana', 'ご', 'go', 'dakuten', 25, NOW(), NOW()),
(UUID(), 'hiragana', 'ざ', 'za', 'dakuten', 26, NOW(), NOW()),
(UUID(), 'hiragana', 'じ', 'ji', 'dakuten', 27, NOW(), NOW()),
(UUID(), 'hiragana', 'ず', 'zu', 'dakuten', 28, NOW(), NOW()),
(UUID(), 'hiragana', 'ぜ', 'ze', 'dakuten', 29, NOW(), NOW()),
(UUID(), 'hiragana', 'ぞ', 'zo', 'dakuten', 30, NOW(), NOW()),
(UUID(), 'katakana', 'ガ', 'ga', 'dakuten', 31, NOW(), NOW()),
(UUID(), 'katakana', 'ギ', 'gi', 'dakuten', 32, NOW(), NOW()),
(UUID(), 'katakana', 'グ', 'gu', 'dakuten', 33, NOW(), NOW()),
(UUID(), 'katakana', 'ゲ', 'ge', 'dakuten', 34, NOW(), NOW()),
(UUID(), 'katakana', 'ゴ', 'go', 'dakuten', 35, NOW(), NOW()),
(UUID(), 'katakana', 'ザ', 'za', 'dakuten', 36, NOW(), NOW()),
(UUID(), 'katakana', 'ジ', 'ji', 'dakuten', 37, NOW(), NOW()),
(UUID(), 'katakana', 'ズ', 'zu', 'dakuten', 38, NOW(), NOW()),
(UUID(), 'katakana', 'ゼ', 'ze', 'dakuten', 39, NOW(), NOW()),
(UUID(), 'katakana', 'ゾ', 'zo', 'dakuten', 40, NOW(), NOW()),

-- 半濁音 - Handakuten (5×2)
(UUID(), 'hiragana', 'ぱ', 'pa', 'handakuten', 41, NOW(), NOW()),
(UUID(), 'hiragana', 'ぴ', 'pi', 'handakuten', 42, NOW(), NOW()),
(UUID(), 'hiragana', 'ぷ', 'pu', 'handakuten', 43, NOW(), NOW()),
(UUID(), 'hiragana', 'ぺ', 'pe', 'handakuten', 44, NOW(), NOW()),
(UUID(), 'hiragana', 'ぽ', 'po', 'handakuten', 45, NOW(), NOW()),
(UUID(), 'katakana', 'パ', 'pa', 'handakuten', 46, NOW(), NOW()),
(UUID(), 'katakana', 'ピ', 'pi', 'handakuten', 47, NOW(), NOW()),
(UUID(), 'katakana', 'プ', 'pu', 'handakuten', 48, NOW(), NOW()),
(UUID(), 'katakana', 'ペ', 'pe', 'handakuten', 49, NOW(), NOW()),
(UUID(), 'katakana', 'ポ', 'po', 'handakuten', 50, NOW(), NOW()),

-- 拗音 - Youon (Hiragana 33条)
(UUID(), 'hiragana', 'きゃ', 'kya', 'youon', 51, NOW(), NOW()),
(UUID(), 'hiragana', 'きゅ', 'kyu', 'youon', 52, NOW(), NOW()),
(UUID(), 'hiragana', 'きょ', 'kyo', 'youon', 53, NOW(), NOW()),
(UUID(), 'hiragana', 'しゃ', 'sha', 'youon', 54, NOW(), NOW()),
(UUID(), 'hiragana', 'しゅ', 'shu', 'youon', 55, NOW(), NOW()),
(UUID(), 'hiragana', 'しょ', 'sho', 'youon', 56, NOW(), NOW()),
(UUID(), 'hiragana', 'ちゃ', 'cha', 'youon', 57, NOW(), NOW()),
(UUID(), 'hiragana', 'ちゅ', 'chu', 'youon', 58, NOW(), NOW()),
(UUID(), 'hiragana', 'ちょ', 'cho', 'youon', 59, NOW(), NOW()),
(UUID(), 'hiragana', 'にゃ', 'nya', 'youon', 60, NOW(), NOW()),
(UUID(), 'hiragana', 'にゅ', 'nyu', 'youon', 61, NOW(), NOW()),
(UUID(), 'hiragana', 'にょ', 'nyo', 'youon', 62, NOW(), NOW()),
(UUID(), 'hiragana', 'ひゃ', 'hya', 'youon', 63, NOW(), NOW()),
(UUID(), 'hiragana', 'ひゅ', 'hyu', 'youon', 64, NOW(), NOW()),
(UUID(), 'hiragana', 'ひょ', 'hyo', 'youon', 65, NOW(), NOW()),
(UUID(), 'hiragana', 'みゃ', 'mya', 'youon', 66, NOW(), NOW()),
(UUID(), 'hiragana', 'みゅ', 'myu', 'youon', 67, NOW(), NOW()),
(UUID(), 'hiragana', 'みょ', 'myo', 'youon', 68, NOW(), NOW()),
(UUID(), 'hiragana', 'りゃ', 'rya', 'youon', 69, NOW(), NOW()),
(UUID(), 'hiragana', 'りゅ', 'ryu', 'youon', 70, NOW(), NOW()),
(UUID(), 'hiragana', 'りょ', 'ryo', 'youon', 71, NOW(), NOW()),
(UUID(), 'hiragana', 'ぎゃ', 'gya', 'youon', 72, NOW(), NOW()),
(UUID(), 'hiragana', 'ぎゅ', 'gyu', 'youon', 73, NOW(), NOW()),
(UUID(), 'hiragana', 'ぎょ', 'gyo', 'youon', 74, NOW(), NOW()),
(UUID(), 'hiragana', 'じゃ', 'ja', 'youon', 75, NOW(), NOW()),
(UUID(), 'hiragana', 'じゅ', 'ju', 'youon', 76, NOW(), NOW()),
(UUID(), 'hiragana', 'じょ', 'jo', 'youon', 77, NOW(), NOW()),
(UUID(), 'hiragana', 'びゃ', 'bya', 'youon', 78, NOW(), NOW()),
(UUID(), 'hiragana', 'びゅ', 'byu', 'youon', 79, NOW(), NOW()),
(UUID(), 'hiragana', 'びょ', 'byo', 'youon', 80, NOW(), NOW()),
(UUID(), 'hiragana', 'ぴゃ', 'pya', 'youon', 81, NOW(), NOW()),
(UUID(), 'hiragana', 'ぴゅ', 'pyu', 'youon', 82, NOW(), NOW()),
(UUID(), 'hiragana', 'ぴょ', 'pyo', 'youon', 83, NOW(), NOW()),

-- 拗音 - Youon (Katakana 33条)
(UUID(), 'katakana', 'キャ', 'kya', 'youon', 84, NOW(), NOW()),
(UUID(), 'katakana', 'キュ', 'kyu', 'youon', 85, NOW(), NOW()),
(UUID(), 'katakana', 'キョ', 'kyo', 'youon', 86, NOW(), NOW()),
(UUID(), 'katakana', 'シャ', 'sha', 'youon', 87, NOW(), NOW()),
(UUID(), 'katakana', 'シュ', 'shu', 'youon', 88, NOW(), NOW()),
(UUID(), 'katakana', 'ショ', 'sho', 'youon', 89, NOW(), NOW()),
(UUID(), 'katakana', 'チャ', 'cha', 'youon', 90, NOW(), NOW()),
(UUID(), 'katakana', 'チュ', 'chu', 'youon', 91, NOW(), NOW()),
(UUID(), 'katakana', 'チョ', 'cho', 'youon', 92, NOW(), NOW()),
(UUID(), 'katakana', 'ニャ', 'nya', 'youon', 93, NOW(), NOW()),
(UUID(), 'katakana', 'ニュ', 'nyu', 'youon', 94, NOW(), NOW()),
(UUID(), 'katakana', 'ニョ', 'nyo', 'youon', 95, NOW(), NOW()),
(UUID(), 'katakana', 'ヒャ', 'hya', 'youon', 96, NOW(), NOW()),
(UUID(), 'katakana', 'ヒュ', 'hyu', 'youon', 97, NOW(), NOW()),
(UUID(), 'katakana', 'ヒョ', 'hyo', 'youon', 98, NOW(), NOW()),
(UUID(), 'katakana', 'ミャ', 'mya', 'youon', 99, NOW(), NOW()),
(UUID(), 'katakana', 'ミュ', 'myu', 'youon', 100, NOW(), NOW()),
(UUID(), 'katakana', 'ミョ', 'myo', 'youon', 101, NOW(), NOW()),
(UUID(), 'katakana', 'リャ', 'rya', 'youon', 102, NOW(), NOW()),
(UUID(), 'katakana', 'リュ', 'ryu', 'youon', 103, NOW(), NOW()),
(UUID(), 'katakana', 'リョ', 'ryo', 'youon', 104, NOW(), NOW()),
(UUID(), 'katakana', 'ギャ', 'gya', 'youon', 105, NOW(), NOW()),
(UUID(), 'katakana', 'ギュ', 'gyu', 'youon', 106, NOW(), NOW()),
(UUID(), 'katakana', 'ギョ', 'gyo', 'youon', 107, NOW(), NOW()),
(UUID(), 'katakana', 'ジャ', 'ja', 'youon', 108, NOW(), NOW()),
(UUID(), 'katakana', 'ジュ', 'ju', 'youon', 109, NOW(), NOW()),
(UUID(), 'katakana', 'ジョ', 'jo', 'youon', 110, NOW(), NOW()),
(UUID(), 'katakana', 'ビャ', 'bya', 'youon', 111, NOW(), NOW()),
(UUID(), 'katakana', 'ビュ', 'byu', 'youon', 112, NOW(), NOW()),
(UUID(), 'katakana', 'ビョ', 'byo', 'youon', 113, NOW(), NOW()),
(UUID(), 'katakana', 'ピャ', 'pya', 'youon', 114, NOW(), NOW()),
(UUID(), 'katakana', 'ピュ', 'pyu', 'youon', 115, NOW(), NOW()),
(UUID(), 'katakana', 'ピョ', 'pyo', 'youon', 116, NOW(), NOW());
